// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDntZCDhvcrOgi0LdqtPCtr-Ob2XZphlbE',
    appId: '1:358496694503:web:f713320b079977da24f242',
    messagingSenderId: '358496694503',
    projectId: 'circlify-112ce',
    authDomain: 'circlify-112ce.firebaseapp.com',
    storageBucket: 'circlify-112ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs19tE_Vb_lcwyHFcWvmoqPSS1PzHvPUM',
    appId: '1:358496694503:android:bfb136b5bf702d8c24f242',
    messagingSenderId: '358496694503',
    projectId: 'circlify-112ce',
    storageBucket: 'circlify-112ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc70NobhjeW6dru6DoOeW9YiqcaGUxT3A',
    appId: '1:358496694503:ios:3c90958fbd1f0c9924f242',
    messagingSenderId: '358496694503',
    projectId: 'circlify-112ce',
    storageBucket: 'circlify-112ce.appspot.com',
    iosBundleId: 'com.example.circlify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc70NobhjeW6dru6DoOeW9YiqcaGUxT3A',
    appId: '1:358496694503:ios:17bf5d5faee773f824f242',
    messagingSenderId: '358496694503',
    projectId: 'circlify-112ce',
    storageBucket: 'circlify-112ce.appspot.com',
    iosBundleId: 'com.example.circlify.RunnerTests',
  );
}
